# Generated by Django 4.0.6 on 2022-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_testadopt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('ligation', models.CharField(max_length=50)),
                ('vaccine', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('pci', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Shelter',
        ),
        migrations.DeleteModel(
            name='TestAdopt',
        ),
    ]
