# Generated by Django 4.0.6 on 2022-08-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_adopt_delete_shelter_delete_testadopt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopt',
            old_name='pci',
            new_name='pic',
        ),
    ]
