# Generated by Django 4.0.6 on 2022-08-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_rename_pci_adopt_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='size',
            field=models.CharField(default=1312, max_length=50),
            preserve_default=False,
        ),
    ]
