# Generated by Django 4.0.6 on 2022-08-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_adopt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='pic',
            field=models.CharField(max_length=250),
        ),
    ]
