# Generated by Django 4.0.6 on 2022-08-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_adopt_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('variety', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('lostdate', models.DateField()),
                ('area', models.CharField(max_length=50)),
                ('pet_jpg', models.CharField(max_length=250)),
            ],
        ),
    ]
