# Generated by Django 4.0.6 on 2022-08-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='picUpload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
